name: Continuous Delivery

on:
  push:
    branches:
      - main
      - feature/kubernetes-setup
      - feature/continuous-delivery
  pull_request:
    branches:
      - main
      - feature/kubernetes-setup
      - feature/continuous-delivery

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    - name: Decode and persist kubeconfig
      run: echo "${{ secrets.KUBECONFIG }}" | base64 -d > kubeconfig

    - name: Deploy to Kubernetes
      run: |
        kubectl --kubeconfig=kubeconfig apply -f k8s/

  deploy-multiple-environments:
    runs-on: ubuntu-latest
    needs: deploy
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/staging' || github.ref == 'refs/heads/develop'

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    - name: Decode and persist kubeconfig
      run: echo "${{ secrets.KUBECONFIG }}" | base64 -d > kubeconfig

    - name: Deploy to environment
      run: |
        if [ "${{ github.ref }}" == "refs/heads/main" ]; then
          kubectl --kubeconfig=kubeconfig apply -f k8s/production/
        elif [ "${{ github.ref }}" == "refs/heads/staging" ]; then
          kubectl --kubeconfig=kubeconfig apply -f k8s/staging/
        elif [ "${{ github.ref }}" == "refs/heads/develop" ]; then
          kubectl --kubeconfig=kubeconfig apply -f k8s/development/
        fi
