name: Feature workflow
on: 
  push:
    branches:
      - 'feature/*'
  workflow_dispatch:

jobs:
  test_frontend:
    name: Test Frontend
    runs-on: ubuntu-latest
    steps:
      - name: Clone down repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.18' # Same Go version as the Docker files

      - name: Install dependencies
        run: go mod tidy
        working-directory: ./frontend

      - name: Build Frontend app
        run: go build -o app .
        working-directory: ./frontend
      
      - name: Run tests
        run: go test -v .
        working-directory: ./frontend
